import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar/app-sidebar";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'InsightAI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/*<header className="flex justify-end items-center p-4 gap-4 h-16">
             <SignedOut>
                <div className="flex justify-center items-center w-full">
                  You are not Signed in
                <SignInButton />
                <SignUpButton />
                </div>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn> 
          </header>*/}
          <main>
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}